### ISSUE TITLE
 How to update wake word？

### ISSUE THREAD

**Issue by isafe** [Sensory/alexa-rpi#1]

**Comment by JHdeVilliers** [comment]
If you're asking about updating this repository, a regular `git pull` in the sensory directory of the wakeWordEngine will suffice.

If you're asking about using a different wake word:

This plug-in contains three versions of the "Alexa" trigger, offering different [resource/performance trade-offs](https://github.com/Sensory/alexa-rpi#performance). The largest/best performing model (spot-alexa-rpi-31000.snsr) is used by default.

If you're interested in a custom or user-enrolled wake word or phrase, please get in touch with [Sensory Sales](http://www.sensory.com/support/contact/us-sales/).
