### ISSUE TITLE
Error happened in the mainLoop of SensoryWakeWord snsrRun()

### ISSUE THREAD

**Issue by JDOlliver** [Sensory/alexa-rpi#10]
The first time I set up Alexa at my Pi 3 everything worked fine with the wakewordagent.

Then I tried this Skript (start_Alexa) which opens all the Terminals at once:
`#!/bin/bash

#Start companion service
cd /home/pi/Desktop/alexa-avs-sample-app/samples
cd companionService && npm start&

#Run the sample app
echo "Starting sample app."
cd /home/pi/Desktop/alexa-avs-sample-app/samples
cd javaclient && mvn exec:exec&
echo "When finished "
read -n1 -r -p "Press space to continue..." key

#Run the Wake Word Engine
cd /home/pi/Desktop/alexa-avs-sample-app/samples
cd wakeWordAgent/src && ./wakeWordAgent -e kitt_ai &
`
It don't worked (no matter with kitt_ai or sensory)
**One day later the three-Terminal-method didn't worked anymore.**

According to the Readme file is this error

> ERROR: An error happened in the mainLoop of SensoryWakeWord snsrRun(): task: Inpus channel audio-pcm: ALSA error: No such file or directory

already fixed.

I set my USB mic as the default soundcard with sudo nano /etc/asound.conf

Thanks
JD

**Comment by JHdeVilliers** [comment]
Please check whether you have an **.asoundrc** file in your home directory. If you do, that configuration will override any changes you made to **/etc/asound.conf**.

**Comment by JDOlliver** [comment]
Thanks JHdeVilliers!
I deleated the .asoundrc file, which brought me to a new Error "Alsa argument" (instead of no such file or directory). Then I found a asound.conf file in the sensory directory and put that code to the /etc/asound.conf. Now everything works fine (hopefully longer than last time). 
I think the problem was the default capture device.

[Solved]
