### ISSUE TITLE
404 Errror for https://github.com/alexa/alexa-avs-sample-app

### ISSUE THREAD

**Issue by optimizedsms** [Sensory/alexa-rpi#13]
In the getting started section of the readme. 
(Quoted below)
The link to the alexa-avs-sample-app does not work.

**Getting Started
This project is a plug-in for the **Alexa AVS sample app project**. Please follow the build and configuration instructions for that project.**

**Comment by JHdeVilliers** [comment]
I've updated the [README](https://github.com/Sensory/alexa-rpi#about-the-project) to acknowledge that the original Alexa AVS sample app project was removed by Amazon.
