### ISSUE TITLE
In the raspberryPi haven't wakeWordAgent

### ISSUE THREAD

**Issue by wzone001** [Sensory/alexa-rpi#14]
I have do automated_install.sh, and i can "npm start" and "mvn exec:exec" success, but when i do "cd wakeWordAgent/src && ./wakeWordAgent -e sensory" have some error-----.wakeWordAgent: No such file or directory......there have somebody can help me ????thanks.....

**Comment by JHdeVilliers** [comment]
It sounds like your run of `automated-install.sh` failed to compile the `wakeWordAgent` code. This is outside the scope of this repository, please check the [AVS sample app issues][1] for a possible resolution.

[1]: https://github.com/alexa/alexa-avs-sample-app/issues

**Comment by wzone001** [comment]
Like you said, when i run of automated_install.sh failed to compile the wakeWordAgent code, the error message is same with do "make" by myself,andthe AVS sample app issues also haven't resolution.
