### ISSUE TITLE
Can this source run on Ubuntu (x86)?

### ISSUE THREAD

**Issue by yxzb** [Sensory/alexa-rpi#16]
I downloaded the source code, and then executed the license script(/bin/lisence.sh) on Ubuntu (x86) and kept reporting errors.

zhx@ubuntu:~/share/doc/sensory2/alexa-rpi$ ./bin/license.sh 
./bin/license.sh: line 49: /home/zhx/share/doc/sensory2/alexa-rpi/bin/sdk-license: cannot execute binary file: Exec format error
Unexpected licensing error encountered. Exiting.
zhx@ubuntu:~/share/doc/sensory2/alexa-rpi$ 
zhx@ubuntu:~/share/doc/sensory2/alexa-rpi$ 
zhx@ubuntu:~/share/doc/sensory2/alexa-rpi$ bash bin/license.sh 
bin/license.sh: line 49: /home/zhx/share/doc/sensory2/alexa-rpi/bin/sdk-license: cannot execute binary file: Exec format error
Unexpected licensing error encountered. Exiting.

I tried a lot，but failed.I wonder if the source code don't support x86

**Comment by JHdeVilliers** [comment]
The binaries in this repository are for the Raspberry Pi only. Also see #7.
