### ISSUE TITLE
Can I get the source code of alexa-rpi !

### ISSUE THREAD

**Issue by future1122** [Sensory/alexa-rpi#21]
**I use the OpenWrt-SDK-ipq806x_gcc-5.2.0_uClibc-1.0.14_eabi.Linux-x86_64 cross compiler to compile the c++ avs-device-sdk . But I have an Error as follows:**

../src/libSENSORY.so: undefined reference to `__stack_chk_guard'
../src/libSENSORY.so: undefined reference to `__ctype_b_loc'
../src/libSENSORY.so: undefined reference to `__printf_chk'
../src/libSENSORY.so: undefined reference to `__isoc99_sscanf'
../src/libSENSORY.so: undefined reference to `__stack_chk_fail'
../src/libSENSORY.so: undefined reference to `__vsnprintf_chk'
../src/libSENSORY.so: undefined reference to `__snprintf_chk'
../src/libSENSORY.so: undefined reference to `__sprintf_chk'
../src/libSENSORY.so: undefined reference to `__fprintf_chk'
collect2: error: ld returned 1 exit status
KWD/Sensory/test/CMakeFiles/SensoryKeywordDetectorTest.dir/build.make:102: recipe for target 'KWD/Sensory/test/SensoryKeywordDetectorTest' failed
make[2]: *** [KWD/Sensory/test/SensoryKeywordDetectorTest] Error 1
CMakeFiles/Makefile2:4445: recipe for target 'KWD/Sensory/test/CMakeFiles/SensoryKeywordDetectorTest.dir/all' failed
make[1]: *** [KWD/Sensory/test/CMakeFiles/SensoryKeywordDetectorTest.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

I think maybe the problem is that the **libsnsr.a** library is not cross compiled by OpenWrt-SDK-ipq806x_gcc-5.2.0_uClibc-1.0.14_eabi.Linux-x86_64 compiler

So I want to try to get the source code and compile it with the OpenWrt-SDK-ipq806x_gcc-5.2.0_uClibc-1.0.14_eabi.Linux-x86_64 compiler 

Maybe The solution is wrong.I don't know  .But if you have any good idea to solve my problem.Please tell me .Thanks .

**Comment by JHdeVilliers** [comment]
The source code is not available. See #7, #15, #17, #20.
