### ISSUE TITLE
cannot execute binary file: 

### ISSUE THREAD

**Issue by meetdave06** [Sensory/alexa-rpi#9]
While running ./bin/license.sh , I get the following error :- 

sensory/alexa-rpi/bin/sdk-license: cannot execute binary file: Exec format error
Unexpected licensing error encountered. Exiting.

Any suggestions will be helpful

**Comment by JHdeVilliers** [comment]
Are you running this on a Raspberry Pi 2 or 3? This library, and the binaries such as `sdk-license`, were built for Raspbian Jesse, running on a CPU that supports ARMv7 instructions.

**Comment by meetdave06** [comment]
Hi @JHdeVilliers 
I was trying to run it on ubuntu. Is there any way to run it on ubuntu ? I tried to modify the script so that it doesn't try to compile alexa-rpi but failed to do so.

**Comment by JHdeVilliers** [comment]
This project is a plug-in for the WakeWordEngine in the [Alexa AVS sample app][1], which supports hands-free use on the Raspberry Pi only. On Intel/AMD Linux, macOS and Windows the AVS project uses push-to-talk.

This repository is the only trial version of TrulyHandsfree that's currently publicly available.
The TrulyHandsfree SDK runs on various other platforms, but you'll have to go through [Sensory Sales][2] to gain access to these.

[1]: https://github.com/alexa/alexa-avs-sample-app#about-the-project
[2]: http://www.sensory.com/support/contact/us-sales/
